Game.create("date"=>"Sat, 01 Aug 2015", "team_name"=>"Baltimore Orioles", "opponent"=>"Tigers", "promotion"=>"Oriole Bird Bobblehead")
Game.create("date"=>"Tue, 14 Apr 2015", "team_name"=>"Boston Red Sox", "opponent"=>"Nationals", "promotion"=>"Wally Bobblehead")
Game.create("date"=>"Thu, 21 May 2015", "team_name"=>"Boston Red Sox", "opponent"=>"Rangers", "promotion"=>"Tiant Bobblehead")
Game.create("date"=>"Tue, 02 Jun 2015", "team_name"=>"Boston Red Sox", "opponent"=>"Twins", "promotion"=>"Napoli Bobblehead")
Game.create("date"=>"Tue, 28 Apr 2015", "team_name"=>"New York Yankees", "opponent"=>"Rays", "promotion"=>"Masahiro Tanaka Bobblehead Night")
Game.create("date"=>"Thu, 18 Jun 2015", "team_name"=>"New York Yankees", "opponent"=>"Marlins", "promotion"=>"Thurman Munson Bobblehead Night")
Game.create("date"=>"Mon, 24 Aug 2015", "team_name"=>"New York Yankees", "opponent"=>"Astros", "promotion"=>"Jacoby Ellsbury Bobblehead Night")
Game.create("date"=>"Wed, 09 Sep 2015", "team_name"=>"New York Yankees", "opponent"=>"Orioles", "promotion"=>"Yankees Peanuts Bobblehead Night - 4th in a series")
Game.create("date"=>"Thu, 10 Sep 2015", "team_name"=>"New York Yankees", "opponent"=>"Blue Jays", "promotion"=>"Babe Ruth Bobblehead Night")
Game.create("date"=>"Sat, 25 Apr 2015", "team_name"=>"Tampa Bay Rays", "opponent"=>"Blue Jays", "promotion"=>"Chris Archer Bobblehead")
Game.create("date"=>"Sat, 09 May 2015", "team_name"=>"Tampa Bay Rays", "opponent"=>"Rangers", "promotion"=>"Evan Longoria Walkup Music Bobblehead")
Game.create("date"=>"Sat, 19 Sep 2015", "team_name"=>"Tampa Bay Rays", "opponent"=>"Orioles", "promotion"=>"Fan Vote Bobblehead")
Game.create("date"=>"Mon, 03 Aug 2015", "team_name"=>"Toronto Blue Jays", "opponent"=>"Twins", "promotion"=>"Russell Martin Bobblehead")
Game.create("date"=>"Sun, 16 Aug 2015", "team_name"=>"Toronto Blue Jays", "opponent"=>"Yankees", "promotion"=>"Bell, Moseby & Barfield Bobblehead presented by TD")
Game.create("date"=>"Sat, 04 Jul 2015", "team_name"=>"Chicago White Sox", "opponent"=>"Orioles", "promotion"=>"Bobby Jenks World Series Moment Bobblehead")
Game.create("date"=>"Sat, 29 Aug 2015", "team_name"=>"Chicago White Sox", "opponent"=>"Mariners", "promotion"=>"Jermaine Dye World Series Moment Bobblehead")
Game.create("date"=>"Sat, 06 Jun 2015", "team_name"=>"Cleveland Indians", "opponent"=>"Orioles", "promotion"=>"Corey Kluber bobblehead")
Game.create("date"=>"Wed, 08 Jul 2015", "team_name"=>"Cleveland Indians", "opponent"=>"Astros", "promotion"=>"Carlos Santana bobblehead")
Game.create("date"=>"Sat, 12 Sep 2015", "team_name"=>"Cleveland Indians", "opponent"=>"Tigers", "promotion"=>"Terry Francona red scooter bobblehead")
Game.create("date"=>"Thu, 25 Jun 2015", "team_name"=>"Detroit Tigers", "opponent"=>"White Sox", "promotion"=>"Victor Martinez Bobblehead")
Game.create("date"=>"Wed, 01 Jul 2015", "team_name"=>"Detroit Tigers", "opponent"=>"Pirates", "promotion"=>"Yoenis Cespedes Bobblehead")
Game.create("date"=>"Mon, 20 Jul 2015", "team_name"=>"Detroit Tigers", "opponent"=>"Mariners", "promotion"=>"David Price Bobblehead")
Game.create("date"=>"Sat, 02 May 2015", "team_name"=>"Houston Astros", "opponent"=>"Mariners", "promotion"=>"Jose Altuve \"Hit Counter\" Bobblehead presented by Goya")
Game.create("date"=>"Fri, 29 May 2015", "team_name"=>"Los Angeles Angels", "opponent"=>"Tigers", "promotion"=>"Matt Shoemaker Bobblehead")
Game.create("date"=>"Fri, 12 Jun 2015", "team_name"=>"Los Angeles Angels", "opponent"=>"Athletics", "promotion"=>"Kole Calhoun Bobblehead")
Game.create("date"=>"Fri, 07 Aug 2015", "team_name"=>"Los Angeles Angels", "opponent"=>"Orioles", "promotion"=>"Garrett Richards Bobblehead")
Game.create("date"=>"Sat, 18 Jul 2015", "team_name"=>"Oakland Athletics", "opponent"=>"Twins", "promotion"=>"Hello Kitty Bobblehead")
Game.create("date"=>"Tue, 18 Aug 2015", "team_name"=>"Oakland Athletics", "opponent"=>"Dodgers", "promotion"=>"Mark McGwire Bobblehead")
Game.create("date"=>"Sat, 18 Apr 2015", "team_name"=>"Seattle Mariners", "opponent"=>"Rangers", "promotion"=>"Felix Hernandez Bobblehead Night")
Game.create("date"=>"Sat, 09 May 2015", "team_name"=>"Seattle Mariners", "opponent"=>"Athletics", "promotion"=>"Fernando Rodney Bobblehead Night")
Game.create("date"=>"Tue, 02 Jun 2015", "team_name"=>"Seattle Mariners", "opponent"=>"Yankees", "promotion"=>"Kyle Seager Bobblehead Night")
Game.create("date"=>"Sat, 11 Jul 2015", "team_name"=>"Seattle Mariners", "opponent"=>"Angels", "promotion"=>"Nelson Cruz Bobblehead Night")
Game.create("date"=>"Sat, 08 Aug 2015", "team_name"=>"Seattle Mariners", "opponent"=>"Rangers", "promotion"=>"Jamie Moyer Mariners Hall of Fame Day - Bobblehead")
Game.create("date"=>"Sat, 22 Aug 2015", "team_name"=>"Seattle Mariners", "opponent"=>"White Sox", "promotion"=>"Robinson Cano Bobblehead Night")
Game.create("date"=>"Tue, 23 Jun 2015", "team_name"=>"Texas Rangers", "opponent"=>"Athletics", "promotion"=>"Dr Pepper/Brookshire's Prince Fielder Bobblehead")
Game.create("date"=>"Wed, 20 May 2015", "team_name"=>"Atlanta Braves", "opponent"=>"Rays", "promotion"=>"Javy Lopez Bobblehead Night")
Game.create("date"=>"Tue, 09 Jun 2015", "team_name"=>"Atlanta Braves", "opponent"=>"Padres", "promotion"=>"David Justice Bobblehead Night")
Game.create("date"=>"Fri, 14 Aug 2015", "team_name"=>"Atlanta Braves", "opponent"=>"D-backs", "promotion"=>"John Smoltz Hall of Fame Bobblehead Night")
Game.create("date"=>"Thu, 10 Sep 2015", "team_name"=>"Atlanta Braves", "opponent"=>"Mets", "promotion"=>"Julio Teheran Bobblehead Night")
Game.create("date"=>"Sat, 11 Jul 2015", "team_name"=>"New York Mets", "opponent"=>"D-backs", "promotion"=>"Juan Lagares Bobblehead")
Game.create("date"=>"Sat, 29 Aug 2015", "team_name"=>"New York Mets", "opponent"=>"Red Sox", "promotion"=>"1986 World Championship Bobblehead")
Game.create("date"=>"Mon, 04 May 2015", "team_name"=>"Washington Nationals", "opponent"=>"Marlins", "promotion"=>"Great Moments in Nationals History: Inaugural Game | Livan Hernandez Bobblehead")
Game.create("date"=>"Thu, 04 Jun 2015", "team_name"=>"Washington Nationals", "opponent"=>"Cubs", "promotion"=>"Great Moments in Nationals History: Nationals Park Walk-Off | Ryan Zimmerman Bobblehead")
Game.create("date"=>"Fri, 25 Sep 2015", "team_name"=>"Washington Nationals", "opponent"=>"Phillies", "promotion"=>"Great Moments in Nationals History: No-Hitter | Jordan Zimmermann Bobblehead")
Game.create("date"=>"Sun, 31 May 2015", "team_name"=>"Chicago Cubs", "opponent"=>"Royals", "promotion"=>"Clark W Flag Bobblehead")
Game.create("date"=>"Sat, 13 Jun 2015", "team_name"=>"Chicago Cubs", "opponent"=>"Reds", "promotion"=>"Joe Maddon Cubs Debut Bobblehead")
Game.create("date"=>"Sat, 25 Jul 2015", "team_name"=>"Chicago Cubs", "opponent"=>"Phillies", "promotion"=>"Jorge Soler Cubs Debut Bobblehead")
Game.create("date"=>"Sat, 22 Aug 2015", "team_name"=>"Chicago Cubs", "opponent"=>"Braves", "promotion"=>"Jon Lester Cubs Debut Bobblehead")
Game.create("date"=>"Sat, 26 Sep 2015", "team_name"=>"Chicago Cubs", "opponent"=>"Pirates", "promotion"=>"TBD Cubs Debut Bobblehead")
Game.create("date"=>"Sat, 11 Apr 2015", "team_name"=>"Cincinnati Reds", "opponent"=>"Cardinals", "promotion"=>"Todd Frazier Bobblehead")
Game.create("date"=>"Sat, 25 Apr 2015", "team_name"=>"Cincinnati Reds", "opponent"=>"Cubs", "promotion"=>"Commemorative Nasty Boys Triple Bobblehead")
Game.create("date"=>"Sat, 16 May 2015", "team_name"=>"Cincinnati Reds", "opponent"=>"Giants", "promotion"=>"Johnny Bench \"Stars of the Queen City\" Bobblehead")
Game.create("date"=>"Sat, 30 May 2015", "team_name"=>"Cincinnati Reds", "opponent"=>"Nationals", "promotion"=>"Billy Hamilton Bobblehead")
Game.create("date"=>"Sat, 06 Jun 2015", "team_name"=>"Cincinnati Reds", "opponent"=>"Padres", "promotion"=>"Barry Larkin \"Stars of the Queen City\" Bobblehead")
Game.create("date"=>"Sat, 20 Jun 2015", "team_name"=>"Cincinnati Reds", "opponent"=>"Marlins", "promotion"=>"Brandon Phillips Bobblehead")
Game.create("date"=>"Sat, 01 Aug 2015", "team_name"=>"Cincinnati Reds", "opponent"=>"Pirates", "promotion"=>"Devin Mesoraco Bobblehead")
Game.create("date"=>"Sat, 12 Sep 2015", "team_name"=>"Cincinnati Reds", "opponent"=>"Cardinals", "promotion"=>"\"Stars of the Queen City\" Bobblehead (Player TBA)")
Game.create("date"=>"Sat, 26 Sep 2015", "team_name"=>"Cincinnati Reds", "opponent"=>"Mets", "promotion"=>"2015 All-Star Player Bobblehead")
Game.create("date"=>"Sun, 26 Apr 2015", "team_name"=>"Milwaukee Brewers", "opponent"=>"Cardinals", "promotion"=>"Wily Peralta Bobblehead")
Game.create("date"=>"Sun, 31 May 2015", "team_name"=>"Milwaukee Brewers", "opponent"=>"D-backs", "promotion"=>"Bud Selig Bobblehead")
Game.create("date"=>"Sun, 14 Jun 2015", "team_name"=>"Milwaukee Brewers", "opponent"=>"Nationals", "promotion"=>"Carlos Gomez 2014 National League All-Star Bobblehead")
Game.create("date"=>"Sun, 28 Jun 2015", "team_name"=>"Milwaukee Brewers", "opponent"=>"Twins", "promotion"=>"Paul Molitor Bobblehead")
Game.create("date"=>"Sun, 19 Jul 2015", "team_name"=>"Milwaukee Brewers", "opponent"=>"Pirates", "promotion"=>"Khris Davis Bobblehead")
Game.create("date"=>"Sun, 09 Aug 2015", "team_name"=>"Milwaukee Brewers", "opponent"=>"Cardinals", "promotion"=>"Bob Uecker Statue Bobblehead")
Game.create("date"=>"Sun, 16 Aug 2015", "team_name"=>"Milwaukee Brewers", "opponent"=>"Phillies", "promotion"=>"Jonathan Lucroy Doubles Record Bobblehead")
Game.create("date"=>"Sun, 30 Aug 2015", "team_name"=>"Milwaukee Brewers", "opponent"=>"Reds", "promotion"=>"Vintage Brewer Bobblehead")
Game.create("date"=>"Sat, 30 May 2015", "team_name"=>"St. Louis Cardinals", "opponent"=>"Dodgers", "promotion"=>"Ozzie Smith Bobblehead")
Game.create("date"=>"Sat, 18 Jul 2015", "team_name"=>"St. Louis Cardinals", "opponent"=>"Mets", "promotion"=>"Matt Carpenter Bobblehead")
Game.create("date"=>"Fri, 24 Jul 2015", "team_name"=>"St. Louis Cardinals", "opponent"=>"Braves", "promotion"=>"Al Hrabosky Bobblehead")
Game.create("date"=>"Fri, 31 Jul 2015", "team_name"=>"St. Louis Cardinals", "opponent"=>"Rockies", "promotion"=>"Lou Brock Bobblehead")
Game.create("date"=>"Sat, 11 Apr 2015", "team_name"=>"Arizona Diamondbacks", "opponent"=>"Dodgers", "promotion"=>"D-backs Hello Kitty Bobblehead")
Game.create("date"=>"Sat, 09 May 2015", "team_name"=>"Arizona Diamondbacks", "opponent"=>"Padres", "promotion"=>"Josh Collmenter Bobblehead courtesy of Arizona Sports 98.7 FM")
Game.create("date"=>"Sat, 06 Jun 2015", "team_name"=>"Arizona Diamondbacks", "opponent"=>"Mets", "promotion"=>"Tony La Russa Bobblehead courtesy of Chevrolet")
Game.create("date"=>"Sat, 18 Jul 2015", "team_name"=>"Arizona Diamondbacks", "opponent"=>"Giants", "promotion"=>"A.J. Pollock Star Wars Bobblehead")
Game.create("date"=>"Sat, 25 Jul 2015", "team_name"=>"Arizona Diamondbacks", "opponent"=>"Brewers", "promotion"=>"Randy Johnson Hall of Fame Bobblehead")
Game.create("date"=>"Sun, 12 Apr 2015", "team_name"=>"Colorado Rockies", "opponent"=>"Cubs", "promotion"=>"Justin Morneau Batting Champ Bobblehead")
Game.create("date"=>"Sun, 07 Jun 2015", "team_name"=>"Colorado Rockies", "opponent"=>"Marlins", "promotion"=>"Road to Rushmore Getaway Day & Troy Tulowitzki bobblehead")
Game.create("date"=>"Fri, 24 Jul 2015", "team_name"=>"Colorado Rockies", "opponent"=>"Reds", "promotion"=>"Charlie Blackmon Bobblehead")
Game.create("date"=>"Sat, 22 Aug 2015", "team_name"=>"Colorado Rockies", "opponent"=>"Mets", "promotion"=>"Star Wars Bobblehead")
Game.create("date"=>"Sun, 23 Aug 2015", "team_name"=>"Colorado Rockies", "opponent"=>"Mets", "promotion"=>"Jorge De La Rosa Bobblehead")
Game.create("date"=>"Tue, 12 May 2015", "team_name"=>"Los Angeles Dodgers", "opponent"=>"Marlins", "promotion"=>"Clayton Kershaw Bobblehead")
Game.create("date"=>"Sat, 23 May 2015", "team_name"=>"Los Angeles Dodgers", "opponent"=>"Padres", "promotion"=>"Adrian Gonzalez Bobblehead")
Game.create("date"=>"Thu, 04 Jun 2015", "team_name"=>"Los Angeles Dodgers", "opponent"=>"Cardinals", "promotion"=>"Kenley Jansen Bobblehead")
Game.create("date"=>"Mon, 06 Jul 2015", "team_name"=>"Los Angeles Dodgers", "opponent"=>"Phillies", "promotion"=>"Maury Wills Bobblehead")
Game.create("date"=>"Sat, 11 Jul 2015", "team_name"=>"Los Angeles Dodgers", "opponent"=>"Brewers", "promotion"=>"Juan Uribe Bobblehead")
Game.create("date"=>"Wed, 29 Jul 2015", "team_name"=>"Los Angeles Dodgers", "opponent"=>"Athletics", "promotion"=>"Yasiel Puig Bobblehead")
Game.create("date"=>"Thu, 13 Aug 2015", "team_name"=>"Los Angeles Dodgers", "opponent"=>"Reds", "promotion"=>"Sandy Koufax  Bobblehead")
Game.create("date"=>"Tue, 01 Sep 2015", "team_name"=>"Los Angeles Dodgers", "opponent"=>"Giants", "promotion"=>"Justin Turner  Bobblehead")
Game.create("date"=>"Wed, 16 Sep 2015", "team_name"=>"Los Angeles Dodgers", "opponent"=>"Rockies", "promotion"=>"Fernando Valenzuela  Bobblehead")
Game.create("date"=>"Wed, 23 Sep 2015", "team_name"=>"Los Angeles Dodgers", "opponent"=>"D-backs", "promotion"=>"Vin Scully  Bobblehead")
Game.create("date"=>"Tue, 14 Apr 2015", "team_name"=>"San Francisco Giants", "opponent"=>"Rockies", "promotion"=>"Madison Bumgarner Postseason MVP Bobblehead")
Game.create("date"=>"Sat, 09 May 2015", "team_name"=>"San Francisco Giants", "opponent"=>"Marlins", "promotion"=>"Hunter Pence 'Fence Catch' Bobblehead")
Game.create("date"=>"Sat, 30 May 2015", "team_name"=>"San Francisco Giants", "opponent"=>"Braves", "promotion"=>"Giants World Champions Postseason Heroes Bobblehead")
Game.create("date"=>"Sat, 13 Jun 2015", "team_name"=>"San Francisco Giants", "opponent"=>"D-backs", "promotion"=>"Giants World Champions Postseason Heroes Bobblehead")
Game.create("date"=>"Sun, 28 Jun 2015", "team_name"=>"San Francisco Giants", "opponent"=>"Rockies", "promotion"=>"Hello Kitty Day Bobblehead")
